### ISSUE TITLE
Include defence calculations in the dice roller dialog when a token is targeted

### ISSUE THREAD

**Issue by zithith** [the-metalworks/cosmere-rpg#105]
**Is your feature request related to a problem? Please describe.**  
Requests on Discord from a number of people that the roller should e able to pick up on the target's defence.

**Suggested Solution**  
When the user has a token targeted and selects a rollable action from an actor sheet, the dialog should include an option to select one of the target's defence values to check against (including none).
Once the roll is made, this selected value (unless none) is compared against the total and the chat message output should display a hit or miss message.
Needs to account for multiple targets too.
Might be worth sitting it behind a world setting feature flag (defaulting to true?) so that GMs can decide if they want to display this information automatically or not.

**Follow-on features**  
* This then opens up the question of do we include a default defence target for rolled actions in general to pre-populate this value?
* Also then to consider if we apply damage as an automation too? Probably only doable for the simplest of calculations and again should be GM toggle-able

**Version**  
0.1.1

**Checklist:**
- [x] I have searched the existing issues to ensure this feature has not already been requested.

**Comment by stanavdb** [comment]
I think before we tackle anything like this we should have some more in-depth discussions/design around rules automation and how/if to implement it.

**Comment by zithith** [comment]
agreed, now how do we go about arranging such a conversation? 🤣

**Comment by zithith** [comment]
No longer necesary, #153 appeases the same requirement
