### ISSUE TITLE
Injury Roll Inline and Add

### ISSUE THREAD

**Issue by Doc-Sun** [the-metalworks/cosmere-rpg#120]
**Is your feature request related to a problem? Please describe.**  
Brought up by @damccull on the forums. To include the duration roll of the amount of time for injury in the same instance as the roll for the injury itself.

I am adding on an addendum myself to then be able to drag it to the character sheet and it auto add the injury to this injury list and fill out the type and duration from the roll. Or if you roll from the token itself to just add the injury right to its related actor/token data. 

**Describe the solution you'd like**  
@damccull showed a picture of a proposed inline roll. 
![image](https://github.com/user-attachments/assets/a2e83954-a571-434c-bd25-9c25f8e92dd5)

Other than my description above of my addon to this request It should have some way to add it right to the sheet. preferably if I roll from the actor it should go right on them. 

**Version**  
0.1.2

**Checklist:**
- [x] I have searched the existing issues to ensure this feature has not already been requested.

**Comment by damccull** [comment]
So my example actually auto rolls it. I couldn't figure out how to put in a click to roll. I like the auto roll personally.

I also like the idea of automatically adding it to the sheet when rolled from the token.

**Comment by Doc-Sun** [comment]
UPDATED to remove the part about 2 clicks! Sorry friend. Wanted to make sure your idea didn't get lost!

**Comment by damccull** [comment]
> UPDATED to remove the part about 2 clicks! Sorry friend. Wanted to make sure your idea didn't get lost!

Naa don't worry about it. Any kind of automation is better than none anyways lol.

**Comment by damccull** [comment]
Out of curiosity, was the part suggested by @Doc-Sun taken care of by someone else? Dragging injuries into the character sheet from chat? If not we should open a separate issue for that.
