### ISSUE TITLE
Rolling injury from sheet displays incorrect actor

### ISSUE THREAD

**Issue by LLilliputian** [the-metalworks/cosmere-rpg#128]
**Describe the bug**  
Currently if you roll and injury it will display it as being rolled for the actor of the token you have selected in the chat instead of the actor of the sheet you've rolled from.
Reported by @deathpote_ on 21/10/2024

**To Reproduce**  
1. Place token of actor A
2. Target actor A
3. Open sheet of actor B
4. Roll injury on actor B's sheet
5. Chat will show injury roll as being for actor A

**Expected behavior**  
If rolling an injury roll from a sheet it should display the actor of the sheet being rolled from.

**Checklist:**
- [x] I have searched the existing issues to ensure this bug has not already been reported

**Comment by MangoFVTT** [comment]
This no longer seems to be reproduceable post the Chat Styling tasks in 0.2.1, likely was fixed as a by product. If the issue arises again, please make a separate issue
