### ISSUE TITLE
Unarmed Stike Fails to Roll

### ISSUE THREAD

**Issue by Doc-Sun** [the-metalworks/cosmere-rpg#157]
**Describe the bug**  
UnarmStrike Fails to roll or output to chat.

**To Reproduce**  
_Steps to reproduce the behavior:_
1. _Go to character sheet with an unarmed attack weapon
2. _Click on the roll for the unarmed attack
3. _See that it does not output

**Expected behavior**  
Unarmed attack should roll (even if it just uses flat damage and not the scaling damage)

**Screenshots**  
![image](https://github.com/user-attachments/assets/1adc4f14-bd3a-4983-b3c3-f333bc698370)

**Foundry VTT Version**  
12.331

**Cosmere RPG System Version**  
0.2.0

**Browser**  
Chrome

**Additional context**  
Tried with a new PC and a already created on from the last update. Same issue

**Checklist:**
- [x] I have searched the existing issues to ensure this bug has not already been reported

**Comment by MangoFVTT** [comment]
@zithith this issue seems to happen explicitly when a damage item has no dice. Since the graze formula (unless overriden) calls @damage.dice automatically, it breaks with this error when parsing the roll:

![image](https://github.com/user-attachments/assets/8f3d2e98-c384-4e5d-81f1-7a73d740c20b)

**Comment by stanavdb** [comment]
Couldn't we just fill the `@damage.dice` with 0 if there are no dice?

**Comment by zithith** [comment]
Possibly, but then your graze damage value for unarmed would be 0, which
isn't right

**Comment by stanavdb** [comment]
> Possibly, but then your graze damage value for unarmed would be 0, which isn't right

 Could we take the first numeric term if there's no dice terms, and if there's no numeric terms fall back to 0?

**Comment by zithith** [comment]
I guess so might be the best compromise solution. I think basically if
there's anything going away after this we can fairly comfortably just claim
the item instance was configured poorly

**Comment by stanavdb** [comment]
Actually, having given it some more thought, the best solution is to have `@damage.dice` to be 0 if there are no dice. It doesn't really make any sense for it to be any other value. 
But then we also have to set the graze override for unarmed strike to something like `max(@damage.dice, 1)`

**Comment by zithith** [comment]
Yeah, I could do this tonight, will grab it

**Comment by zithith** [comment]
> Actually, having given it some more thought, the best solution is to have `@damage.dice` to be 0 if there are no dice. It doesn't really make any sense for it to be any other value. 
> But then we also have to set the graze override for unarmed strike to something like `max(@damage.dice, 1)`

Yeah I think this works. Will need to honour the scaling damage on the unarmed attack though

**Comment by stanavdb** [comment]
> Yeah I think this works. Will need to honour the scaling damage on the unarmed attack though

That should just happen automatically though right? If `@damage.dice` just takes the value of all dice rolled.

**Comment by zithith** [comment]
It'll rely on the output of #91 but I think the point stands about the fact that we just manually override the unarmed item by default.
Base unarmed damage will be `@unarmedDamage + @mod` while the graze override would be that without the mod
Then anyone else who wants to do flat damage will just see that they have to override it or get a default of 1

**Comment by MangoFVTT** [comment]
@zithith i would make it @unarmed or @unarmed.dice (which could also be a flat number ofc). all the formula attributes i've ever seen are single words or dot-connected, it looks weird for it to be 2 words

**Comment by MangoFVTT** [comment]
Btw another simply way to resolve this would be to just make the basic unarmed damage 1d1, which would still be a 1 but count as a die term 😅

**Comment by zithith** [comment]
> Btw another simply way to resolve this would be to just make the basic unarmed damage 1d1, which would still be a 1 but count as a die term 😅 

I... I don't hate this 😂
Would have to be something like `(@unarmed.scalar)d1`, but it could work...
Reeeal workaround.

Or whatever the term is. I appreciate unarmedDamage is unlikely to make the cut, it was just for demonstration purposes. This can be decided in #91
