### ISSUE TITLE
Two Missing tables from the beta rule book.

### ISSUE THREAD

**Issue by Doc-Sun** [the-metalworks/cosmere-rpg#183]
**Is your feature request related to a problem? Please describe.**  
We have an injury duration table but not their effects table or the shardblade injury table

![image](https://github.com/user-attachments/assets/2fa62215-4689-435e-8e0a-cddcf1cd5e91)
![image](https://github.com/user-attachments/assets/5e067433-9cce-4f61-bb0a-81963bfec773)

**Describe the solution you'd like**  
add those tables

**Version**  
0.2.1

**Checklist:**
- [ ] I have searched the existing issues to ensure this feature has not already been requested.

**Comment by zithith** [comment]
Closing as effects table is done, Shardblade one will be included as part of the stormlight module repo
